name: Trigger Karate Tests
on: [push]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.KARATE_REPO_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/raakeshdev20/karate-change-impact-test/dispatches \
          -d '{"event_type": "dev_push"}'